export { default as Trend } from './trend/Trend';
export { default as Home } from './home/Home';
export { default as Songs } from './songs/Songs';
export { default as NotFound } from './notFound/NotFound';
export { default as Search } from './search/Search';
export { default as ArtistHome } from './artists/ArtistHome';
export { default as Artist } from './artists/Artist';
export { default as AlbumHome } from './albums/AlbumHome';
export { default as Album } from './albums/Album';
